## App configs
app:
  name: "Арендатор нежен"
  description: "..."

## Database configs
database:
  url: "jdbc:postgresql://localhost:5432/"
  driver: "org.postgresql.Driver"
  username: ""
  password: ""
## Server configs
server:
  port: 8080

## Configuring spring actuator
management:
  server:
    port: 8090
#  endpoints:
#    web:
#      exposure:
#        include: *
#  endpoint:
#    shutdown:
#      enabled: true

## Configuring info endpoint
info:
  java-version: ${java.version}
  os-name: ${os.name}
  os-version: ${os.version}
  Application-info:
    name: ${app.name}
    description: ${app.description}
    version: ${version}
